version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ../..:/workspaces:cached
      - $USERPROFILE/.aspnet/https:/workspaces/.aspnet/https
    network_mode: service:mysql
    command: sleep infinity
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/volumes/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/volumes/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
