name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

env:
  NUXT_APP_LOCATION: "/src/NuxtSample/"
  NUXT_AZURE_WEBAPP_NAME: "WebSampleApp2024"

jobs:
  nuxt_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: install modules
        run: npm --prefix src/NuxtSample ci

      - name: generate nuxt
        run: npx --prefix src/NuxtSample nuxi generate

      - name: Build And Deploy To Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.NUXT_APP_LOCATION }} # App source code path
          api_location: "https://websamplewebapi2024.azurewebsites.net/" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
