name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main

env:
  MVC_APP_LOCATION: "src/AspNetCoreSample.Mvc"
  MVC_AZURE_WEBAPP_NAME: "WebSampleApp2024" # Azure Web Appの名前
  WEBAPI_APP_LOCATION: "src/AspNetCoreSample.WebApi"
  WEBAPI_AZURE_WEBAPP_NAME: "WebSampleWebApi2024" # Azure Web Appの名前
  NUXT_APP_LOCATION: "/src/NuxtSample/"
  NUXT_AZURE_WEBAPP_NAME: "WebSampleApp2024"

jobs:
  mvc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build with dotnet
        run: dotnet build --configuration Release --framework net8.0
        working-directory: ${{ env.MVC_APP_LOCATION }}

      - name: Publish app for deployment
        run: |
          dotnet publish -c Release -o published --framework net8.0
        working-directory: ${{ env.MVC_APP_LOCATION }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.MVC_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.MVC_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.MVC_APP_LOCATION }}/published

  webapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build with dotnet
        run: dotnet build --configuration Release --framework net8.0
        working-directory: ${{ env.WEBAPI_APP_LOCATION }}

      - name: Publish app for deployment
        run: |
          dotnet publish -c Release -o published --framework net8.0
        working-directory: ${{ env.WEBAPI_APP_LOCATION }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPI_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.WEBAPI_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WEBAPI_APP_LOCATION }}/published

  nuxt_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: install modules
        run: npm --prefix src/NuxtSample ci

      - name: generate nuxt
        run: npm --prefix src/NuxtSample run generate

      - name: Build And Deploy To Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.NUXT_APP_LOCATION }} # App source code path
          api_location: "https://websamplewebapi2024.azurewebsites.net/" # Api source code path - optional
          output_location: ".output/public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
